#### read me ####

# the purpose of this script is to compare ArcGIS-generated catchment characterizations by Alex Webster with those generated by Stevan Earl via streamstats in R
# this is only possible for the NM sites

#### libraries ####

library(tidyverse)

#### load data ####

arc = read.csv("data_raw/VCNP_grab_WSs_area_slope_aspect.csv")
arc$Area_sqkm = arc$Area_sqmet/1000000
arc$X = NULL
arc$X.1 = NULL
arc = arc[1:7,1:7]

Rstats = read.csv("data_raw/nm_streamstats_stats.csv")

# make R data long
Rstats_wide = Rstats %>%
  select(name, location_id, value) %>%
  spread(name, value)

Rstats_wide$Area_sqkm = Rstats_wide$`Drainage Area`*2.59

#### match names ####

arc$WShed_Name

unique(Rstats$location_id)

key = data.frame(WShed_Name = arc$WShed_Name,
                 location_id = c("Indios Creek - above burn",
                            "Sulfur Creek",
                            "san_antonio_custom",
                            "Redondo Creek",
                            "East Fork Jemez River",
                            "Indios Creek",
                            "San Antonio Creek - Toledo"))

arc = left_join(arc, key, by="WShed_Name")

Rstats = left_join(Rstats, key, by="location_id")
Rstats_wide = left_join(Rstats_wide, key, by="location_id")

#### visualize data ####

# watershed area
area_R = Rstats_wide %>% select(location_id, Area_sqkm)
area_R$source = "R"
area_arc = arc %>% select(location_id, Area_sqkm)
area_arc$source = "arc"
area = rbind(area_arc, area_R)
area.p = ggplot()+
  geom_col(data = area, aes(x = location_id, y = Area_sqkm, fill=source), position = "dodge") + 
  theme_classic() + 
  theme(axis.text.x=element_text(angle=45, hjust=1))

# watershed slope
slope_R = Rstats_wide %>% select(location_id, 'Mean Basin Slope from 30m DEM ft/ft')
slope_R$Slope_deg = (atan(slope_R$`Mean Basin Slope from 30m DEM ft/ft`))*57.2958
slope_R$`Mean Basin Slope from 30m DEM ft/ft`=NULL
#names(slope_R) = c("location_id", "Slope_deg")
slope_R$source = "R"
slope_arc = arc %>% select(location_id, Slope_deg)
slope_arc$source = "arc"
slope = rbind(slope_arc, slope_R)
slope.p = ggplot()+
  geom_col(data = slope, aes(x = location_id, y = Slope_deg, fill=source), position = "dodge") + 
  theme_classic() + 
  theme(axis.text.x=element_text(angle=45, hjust=1))

gridExtra::grid.arrange(area.p, slope.p)
